"""Arrow determination step template (Phase 2c).

NOTE: In the current pipeline, arrow determination uses a heuristic fallback
in runner.py rather than executing this template as an LLM step. The template
is preserved for backward compatibility and future use.
"""
from __future__ import annotations

from pipeline.types import StepConfig
from pipeline.prompts.shared_blocks import (
    DIFFERENTIAL_OUTPUT_RULES,
    STRICT_GUARDRAILS,
    SCHEMA_HELP,
    MAX_OUTPUT_TOKENS,
    DYNAMIC_SEARCH_THRESHOLD,
)


def step2c_arrow_template() -> StepConfig:
    """Arrow determination template for a single interactor (Phase 2c)."""
    instruction = "\n".join([
        "╔═══════════════════════════════════════════════════════════════╗",
        "║  STEP 2c: ARROW DETERMINATION FOR {INTERACTOR}               ║",
        "╚═══════════════════════════════════════════════════════════════╝",
        "",
        "QUERY PROTEIN: {ctx_json.main}",
        "INTERACTOR: {INTERACTOR}",
        "",
        "FUNCTIONS AFFECTED BY THEIR INTERACTION:",
        "{FUNCTIONS_LIST}",
        "",
        "╔═══════════════════════════════════════════════════════════════╗",
        "║  MANDATORY STEP 0: READ THE BIOLOGY FIRST (DO NOT SKIP!)     ║",
        "╚═══════════════════════════════════════════════════════════════╝",
        "",
        "Before assigning ANY direction or arrow, you MUST first research and state:",
        "",
        "A) What is {INTERACTOR}'s normal biological role?",
        "   - What does {INTERACTOR} DO in the cell?",
        "   - What processes does {INTERACTOR} participate in?",
        "",
        "B) What is {ctx_json.main}'s normal biological role?",
        "   - What does {ctx_json.main} DO in the cell?",
        "",
        "C) In the published literature about the {ctx_json.main}-{INTERACTOR} interaction:",
        "   - WHO ACTS ON WHOM? Read the papers carefully!",
        "   - Does {INTERACTOR} act on {ctx_json.main}? (= primary_to_main / UPSTREAM)",
        "   - Or does {ctx_json.main} act on {INTERACTOR}? (= main_to_primary / DOWNSTREAM)",
        "   - If BOTH act on each other, create separate functions for each direction",
        "",
        "Write out your Step 0 analysis in the thinking phase BEFORE proceeding!",
        "",
        "╔═══════════════════════════════════════════════════════════════╗",
        "║  CRITICAL DIRECTIONALITY RULES (MOST COMMON ERROR!)          ║",
        "╚═══════════════════════════════════════════════════════════════╝",
        "",
        "The MOST COMMON ERROR is marking upstream interactors as downstream.",
        "An interactor is UPSTREAM (primary_to_main) when it acts ON the query protein.",
        "An interactor is DOWNSTREAM (main_to_primary) when the query protein acts ON it.",
        "",
        "DIRECTION DECISION GUIDE:",
        "",
        "If {INTERACTOR} does ANY of these TO {ctx_json.main}:",
        "  → PROTECTS, STABILIZES, SHIELDS, CHAPERONES {ctx_json.main}",
        "  → PHOSPHORYLATES, UBIQUITINATES, ACETYLATES {ctx_json.main}",
        "  → DEGRADES, CLEAVES, PROCESSES {ctx_json.main}",
        "  → SCAFFOLDS, RECRUITS, LOCALIZES {ctx_json.main}",
        "  → REGULATES expression/levels/activity of {ctx_json.main}",
        "  Then direction = 'primary_to_main' (UPSTREAM: {INTERACTOR} → {ctx_json.main})",
        "",
        "If {ctx_json.main} does ANY of these TO {INTERACTOR}:",
        "  → PHOSPHORYLATES, UBIQUITINATES, DEUBIQUITINATES {INTERACTOR}",
        "  → ACTIVATES, INHIBITS, MODULATES {INTERACTOR}",
        "  → CLEAVES, PROCESSES, DEGRADES {INTERACTOR}",
        "  → RECRUITS, SCAFFOLDS {INTERACTOR}",
        "  Then direction = 'main_to_primary' (DOWNSTREAM: {ctx_json.main} → {INTERACTOR})",
        "",
        "╔═══════════════════════════════════════════════════════════════╗",
        "║  EVERY FUNCTION HAS EXACTLY ONE DIRECTION                     ║",
        "╚═══════════════════════════════════════════════════════════════╝",
        "",
        "The only valid direction values are 'main_to_primary' and 'primary_to_main'.",
        "Each function describes ONE specific biological process with ONE direction.",
        "Even for symmetric binding (Co-IP, Y2H), pick the dominant agent.",
        "",
        "If {INTERACTOR} and {ctx_json.main} affect each other in DIFFERENT ways:",
        "  → Create SEPARATE function entries for each direction",
        "  → Function A (where {ctx_json.main} acts on {INTERACTOR}): interaction_direction = 'main_to_primary'",
        "  → Function B (where {INTERACTOR} acts on {ctx_json.main}): interaction_direction = 'primary_to_main'",
        "",
        "Example: RAD23A and ATXN3 interact. RAD23A stabilizes ATXN3 (upstream).",
        "WRONG: interaction_direction = 'main_to_primary' (implies ATXN3 → RAD23A)",
        "RIGHT: interaction_direction = 'primary_to_main' (RAD23A → ATXN3, RAD23A stabilizes ATXN3)",
        "",
        "═══════════════════════════════════════════════════════════════",
        "YOUR TASK FOR EACH FUNCTION:",
        "═══════════════════════════════════════════════════════════════",
        "",
        "For EACH function, determine THREE things:",
        "",
        "1. INTERACTION DIRECTION",
        "   - Based on Step 0 analysis: WHO acts on WHOM for THIS function?",
        "   - 'main_to_primary': {ctx_json.main} acts on {INTERACTOR}",
        "   - 'primary_to_main': {INTERACTOR} acts on {ctx_json.main}",
        "   - Only 'main_to_primary' or 'primary_to_main' are valid direction values",
        "",
        "2. INTERACTION EFFECT (on the DOWNSTREAM PROTEIN)",
        "   - Research the NORMAL ROLE of the downstream protein",
        "   - Does this interaction ENHANCE or OPPOSE that protein's normal function?",
        "   - Set interaction_effect: 'activates', 'inhibits', or 'regulates'",
        "",
        "3. FUNCTION EFFECT (on the FUNCTION itself - verify existing arrow)",
        "   - The function arrow was set in Step 2a - verify it's correct",
        "   - This CAN differ from interaction_effect!",
        "",
        "═══════════════════════════════════════════════════════════════",
        "EXAMPLE 1: ATXN3-VCP interaction → ERAD (DOWNSTREAM)",
        "═══════════════════════════════════════════════════════════════",
        "",
        "Step 0 analysis: ATXN3 is a deubiquitinase. VCP/p97 drives ERAD.",
        "Literature says: ATXN3 modulates VCP's ERAD activity.",
        "WHO acts on whom? ATXN3 acts on VCP → main_to_primary",
        "",
        "Function: {'function': 'ERAD', 'arrow': 'inhibits'}",
        "→ interaction_direction: 'main_to_primary' (ATXN3 → VCP)",
        "→ interaction_effect: 'inhibits' (ATXN3 inhibits VCP's ERAD)",
        "→ arrow: 'inhibits' (ERAD is inhibited) ✓",
        "",
        "═══════════════════════════════════════════════════════════════",
        "EXAMPLE 2: RAD23A-ATXN3 interaction → ATXN3 Stability (UPSTREAM!)",
        "═══════════════════════════════════════════════════════════════",
        "",
        "Step 0 analysis: RAD23A is a ubiquitin receptor/proteasome shuttle.",
        "Literature says: RAD23A binds ATXN3 via UbS2 domain and SHIELDS it",
        "from proteasomal degradation. RAD23A STABILIZES ATXN3.",
        "WHO acts on whom? RAD23A acts on ATXN3 → primary_to_main (UPSTREAM!)",
        "",
        "Function: {'function': 'ATXN3 Stability', 'arrow': 'activates'}",
        "→ interaction_direction: 'primary_to_main' (RAD23A → ATXN3)",
        "→ interaction_effect: 'activates' (RAD23A enhances ATXN3 stability)",
        "→ arrow: 'activates' (ATXN3 stability is increased) ✓",
        "",
        "WRONG ANSWER: interaction_direction: 'main_to_primary'",
        "  This would mean ATXN3 regulates RAD23A - that's BACKWARDS!",
        "  RAD23A protects ATXN3, not the other way around.",
        "",
        "═══════════════════════════════════════════════════════════════",
        "EXAMPLE 3: When effects DIFFER (inhibit protein → activate function)",
        "═══════════════════════════════════════════════════════════════",
        "",
        "Protein A inhibits Protein B, which normally REPRESSES Function X",
        "→ Function X is RELEASED from repression → activated!",
        "→ interaction_direction: 'main_to_primary' (A → B)",
        "→ interaction_effect: 'inhibits' (A inhibits B protein)",
        "→ arrow: 'activates' (Function X is activated - DIFFERS from interaction_effect!)",
        "",
        "═══════════════════════════════════════════════════════════════",
        "FINAL VALIDATION (MANDATORY!):",
        "═══════════════════════════════════════════════════════════════",
        "",
        "Before returning, for EACH function, ask yourself:",
        "  'If I read this interaction_direction to a biologist, would they agree?'",
        "  'Does the literature support that [upstream protein] acts on [downstream protein]?'",
        "",
        "Common mistakes to catch:",
        "- Interactor PROTECTS/STABILIZES query protein but marked as main_to_primary",
        "- Interactor PHOSPHORYLATES/MODIFIES query protein but marked as main_to_primary",
        "- Query protein is the SUBSTRATE of the interactor but marked as main_to_primary",
        "",
        "OUTPUT STRUCTURE:",
        "Update EACH function in the interactor's functions array with:",
        "{",
        "  'function': '<function name>',",
        "  'interaction_direction': 'main_to_primary' | 'primary_to_main',",
        "  'interaction_effect': 'activates' | 'inhibits' | 'regulates',",
        "  'arrow': 'activates' | 'inhibits',  // Keep existing or correct if wrong",
        "  'cellular_process': '...',",
        "  'effect_description': '...',",
        "  ...",
        "}",
        "",
        "Also add interactor-level summary:",
        "{",
        "  'primary': '{INTERACTOR}',",
        "  'direction': 'main_to_primary' | 'primary_to_main',",
        "  'arrow': 'activates' | 'inhibits' | 'regulates',",
        "  'intent': '<mechanism>',",
        "  'functions': [<updated function entries>]",
        "}",
        "",
        "NOTE: Interactor-level 'direction' is the DOMINANT direction across all",
        "functions. If functions span both directions, pick the one with the strongest",
        "evidence. Each individual function MUST have a single direction.",
        "",
        "Search freely to understand both proteins' normal biological roles!",
    ])
    return StepConfig(
        name="step2c_arrow_TEMPLATE",
        model="gemini-3-flash-preview", #WAS GEMINI-3.1-PRO
        use_google_search=True,
        thinking_level="high",
        max_output_tokens=65536,
        search_dynamic_mode=True,
        search_dynamic_threshold=DYNAMIC_SEARCH_THRESHOLD,
        expected_columns=["ctx_json", "step_json"],
        system_prompt=None,
        prompt_template=(
            DIFFERENTIAL_OUTPUT_RULES
            + "\n\n"
            + STRICT_GUARDRAILS
            + "\n\n"
            + instruction
            + "\n\n"
            + SCHEMA_HELP
            + "\n\n"
            + "Return ONLY JSON with updated arrow/direction/intent for {INTERACTOR}"
        ),
    )
