"""baseline — initialize the schema from SQLAlchemy metadata.

Revision ID: 000000000000
Revises:
Create Date: 2026-04-15

Re-implements the baseline so a fresh Postgres instance can be brought
up entirely via ``alembic upgrade head`` (previously the baseline was a
no-op, which assumed schema was already created via legacy
``scripts/migrate_*.py`` one-shots OR via ``app.py``'s import-time
``db.create_all()``).

Strategy: import ``models.db.metadata`` and call ``create_all`` against
the bound connection. Idempotent — ``create_all`` skips tables/indexes
that already exist, so this migration is safe to re-run on a populated
database.

For new databases, ``alembic upgrade head`` now produces:
  1. baseline (this migration) → CREATE TABLE / CREATE INDEX for every model
  2. 20260420_0001 drop_dead_tables → cleans up legacy tables (no-op on fresh DB)
  3. 20260429_0002 add_function_context_index → CREATE INDEX CONCURRENTLY

For existing databases, ``alembic stamp head`` is still the right move
(idempotent ``create_all`` won't recreate existing tables, but the
revision pointer needs to be set).
"""
from __future__ import annotations

from alembic import op


revision = "000000000000"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create every table/index defined on ``models.db.metadata``.

    Uses ``create_all`` on the active connection rather than autogenerated
    DDL so the migration tracks the model definitions automatically. The
    cost: ``alembic --sql`` (offline mode) cannot pre-render DDL, because
    ``create_all`` requires a live connection. For offline DDL generation,
    use ``alembic upgrade --sql`` only on later revisions where this
    baseline is already stamped.
    """
    bind = op.get_bind()
    # Late import so importing this module (e.g., for inspection) doesn't
    # pull in the ORM models — only ``upgrade()`` actually needs them.
    from models import db
    db.metadata.create_all(bind=bind, checkfirst=True)


def downgrade() -> None:
    """Drop every table/index defined on ``models.db.metadata``.

    Mirror of ``upgrade``. Used only by ``alembic downgrade base`` — the
    full schema teardown. Production should never run this; it's here to
    keep the migration symmetric.
    """
    bind = op.get_bind()
    from models import db
    db.metadata.drop_all(bind=bind, checkfirst=True)
